### ISSUE TITLE
Not show images.

### ISSUE THREAD

**Issue by ArmMkr** [rishabhtayal/RTFacebookAlbum#3]
i run this application, but it is not show facebook images.

**Comment by ArmMkr** [comment]
Anyone can help?

**Comment by rishabhtayal** [comment]
I will take a look today.

**Comment by ArmMkr** [comment]
OK.Thank you. i need your help.

Четверг, 19 марта 2015, 4:57 -07:00 от Rishabh Tayal <notifications@github.com>:

**Comment by rishabhtayal** [comment]
@ArmMkr fixed!

**Comment by ArmMkr** [comment]
Thank You  very much..!!! This is very good example for learning Facebook sdk in ios. Thanks.

**Comment by rishabhtayal** [comment]
@ArmMkr Thanks. Any feedback will be appreciated.
